name: 'Update .NET SDK'
description: 'Attempts to update the version of the .NET SDK used by the repository''s global.json file.'
author: 'Martin Costello'
branding:
  icon: 'refresh-cw'
  color: 'blue'
inputs:
  repo-token:
    description: 'The GitHub access token to use to create a Pull Request for any SDK update to the repository.'
    required: true
  branch-name:
    description: 'The optional Git branch name to use.'
    required: false
    default: ''
  channel:
    description: 'The optional .NET release channel to download the SDK for (2.1, 3.1, 5.0, etc.).'
    required: false
    default: ''
  close-superseded:
    description: 'If true, any existing pull requests superseded by any pull request opened by the action are closed.'
    required: false
    default: true
  commit-message:
    description: 'The optional Git commit message to use.'
    required: false
    default: ''
  commit-message-prefix:
    description: 'The optional Git commit message prefix to use if commit-message is not specified.'
    required: false
    default: ''
  generate-step-summary:
    description: 'If true, will output a summary of any .NET SDK update to $GITHUB_STEP_SUMMARY.'
    required: false
    default: true
  global-json-file:
    description: 'The optional path to the global.json file to update.'
    required: false
    default: './global.json'
  labels:
    description: 'The optional comma-separated label(s) to apply to Pull Requests generated by the action.'
    required: false
    default: ''
  repo:
    description: 'The optional GitHub repository to generate the pull request against.'
    required: false
    default: ${{ github.repository }}
  quality:
    description: 'The optional value to specify using the latest build of the specified quality in the channel.'
    required: false
    default: ''
  user-email:
    description: 'The optional email address to use for the Git commit.'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  user-name:
    description: 'The optional user name to use for the Git commit.'
    required: false
    default: 'github-actions[bot]'
  dry-run:
    description: 'If true, the action will not push changes to GitHub.'
    required: false
    default: false
outputs:
  branch-name:
    description: 'The name of the Git branch associated with the Pull Request created by the action if the .NET SDK is updated.'
  pull-request-number:
    description: 'The number of the Pull Request created by the action if the .NET SDK is updated.'
  pull-request-html-url:
    description: 'The HTML URL of the Pull Request created by the action if the .NET SDK is updated.'
  pull-requests-closed:
    description: 'A JSON array of the numbers of any pull requests that were closed as superseded.'
  sdk-updated:
    description: 'Whether the .NET SDK was updated by the action.'
  sdk-version:
    description: 'The latest version of the .NET SDK for the specified channel when the action completed.'
  security:
    description: 'Whether any .NET SDK update includes security fixes.'
runs:
  using: 'node20'
  main: 'dist/index.js'
