name: update-dotnet-sdk-test

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  update-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      global-json-file: './_global.json'
      labels: dependencies
      update-nuget-packages: false
    secrets:
      repo-token: ${{ secrets.GITHUB_TOKEN }}

  print-outputs:
    name: Print outcome
    needs: update-sdk
    runs-on: ubuntu-latest

    steps:

    - name: Print update details
      run: |
        echo "SDK updated: ${{ needs.update-sdk.outputs.sdk-updated }}"
        echo "SDK version: ${{ needs.update-sdk.outputs.sdk-version }}"
        echo "Security: ${{ needs.update-sdk.outputs.security }}"
        echo "PR number: ${{ needs.update-sdk.outputs.pull-request-number }}"
        echo "PR URL: ${{ needs.update-sdk.outputs.pull-request-html-url }}"
