name: update-dotnet-sdk

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    name: Update .NET SDK

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update .NET SDK
      id: update
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        global-json-file: './_global.json'
        labels: dependencies

    - name: Print outputs
      run: |
        echo "PR number: ${{ steps.update.outputs.pull-request-number }}"
        echo "PR URL: ${{ steps.update.outputs.pull-request-html-url }}"
        echo "SDK Updated? ${{ steps.update.outputs.sdk-updated }}"
        echo "SDK version: ${{ steps.update.outputs.sdk-version }}"
